### ISSUE TITLE
Allow specifying colors of only first columns?

### ISSUE THREAD

**Issue by fralau** [Justintime50/pretty-tables#4]
Thanks for this package! I like this feature of colored tables. Ideally, one should be able to specify a list of colors that does not correspond to the header (shorter or longer). 

For example, one could specify the first 2 colors (red and green) and left the others unspecified, i.e. assume that they have the default color. 

```python
colors = [
    pretty_tables.Colors.red,
    pretty_tables.Colors.green
    # next columns are default color
]
```
Wouldn't that make writing the code much easier,  and would make the code more robust if the no of columns changes?

**Comment by Justintime50** [comment]
Sure, that's a sane thing to do when nothing is provided. I've put up PR #5, care to take a look and see if that does what you are looking for?

**Comment by fralau** [comment]
Perfect, thanks! 👍
